#ifndef QSERIALADAPTERI7540D_GLOBAL_HPP
#define QSERIALADAPTERI7540D_GLOBAL_HPP

#include <QtCore/qglobal.h>

#if defined(QSERIALADAPTERI7540D_LIBRARY)
#  define QSERIALADAPTERI7540D_EXPORT Q_DECL_EXPORT
#else
#  define QSERIALADAPTERI7540D_EXPORT Q_DECL_IMPORT
#endif

#endif // QSERIALADAPTERI7540D_GLOBAL_HPP
